#pragma once
/*___INFO__MARK_BEGIN_NEW__*/
/***************************************************************************
 *
 *  Copyright 2024 HPC-Gridware GmbH
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 ***************************************************************************/
/*___INFO__MARK_END_NEW__*/
#include "cull/cull_list.h"

/*----------------------------------------------------
 *
 * 1. sge_boundaries.h
 *
 *    is included by every file of group 2
 *    defines boundaries of all lists
 *
 * 2. sge_jobL.h ...
 *
 *    is used to define a specific list like:
 *    - job list
 *    - ...
 *
 *--------------------------------------------------
 */

/* BASIC_UNIT and MAX_DESCR_SIZE is defined in cull/cull_list.h */

enum NameSpaceBoundaries {

   JB_LOWERBOUND = 1*BASIC_UNIT,
   JB_UPPERBOUND = JB_LOWERBOUND + 3*BASIC_UNIT - 1,

   JRS_LOWERBOUND = JB_UPPERBOUND + 1,
   JRS_UPPERBOUND = JRS_LOWERBOUND + 2*BASIC_UNIT - 1,

   QU_LOWERBOUND = JRS_UPPERBOUND + 1,
   QU_UPPERBOUND = QU_LOWERBOUND + 3*BASIC_UNIT - 1,

   EH_LOWERBOUND = QU_UPPERBOUND + 1,
   EH_UPPERBOUND = EH_LOWERBOUND + 2*BASIC_UNIT - 1,

   AH_LOWERBOUND = EH_UPPERBOUND + 1,
   AH_UPPERBOUND = AH_LOWERBOUND + 2*BASIC_UNIT - 1,

   SH_LOWERBOUND = AH_UPPERBOUND + 1,
   SH_UPPERBOUND = SH_LOWERBOUND + 2*BASIC_UNIT - 1,

   AN_LOWERBOUND = SH_UPPERBOUND + 1,
   AN_UPPERBOUND = AN_LOWERBOUND + 2*BASIC_UNIT - 1,

   HL_LOWERBOUND = AN_UPPERBOUND + 1,
   HL_UPPERBOUND = HL_LOWERBOUND + 2*BASIC_UNIT - 1,

   HS_LOWERBOUND = HL_UPPERBOUND + 1,
   HS_UPPERBOUND = HS_LOWERBOUND + 2*BASIC_UNIT - 1,

   ET_LOWERBOUND = HS_UPPERBOUND + 1,
   ET_UPPERBOUND = ET_LOWERBOUND + 2*BASIC_UNIT - 1,

   EV_LOWERBOUND = ET_UPPERBOUND + 1,
   EV_UPPERBOUND = EV_LOWERBOUND + 2*BASIC_UNIT - 1,

   EVS_LOWERBOUND = EV_UPPERBOUND + 1,
   EVS_UPPERBOUND = EVS_LOWERBOUND + 2*BASIC_UNIT - 1,

   CE_LOWERBOUND = EVS_UPPERBOUND + 1,
   CE_UPPERBOUND = CE_LOWERBOUND + 2*BASIC_UNIT - 1,

   LR_LOWERBOUND = CE_UPPERBOUND + 1,
   LR_UPPERBOUND = LR_LOWERBOUND + 2*BASIC_UNIT - 1,

   OR_LOWERBOUND = LR_UPPERBOUND + 1,
   OR_UPPERBOUND = OR_LOWERBOUND + 2*BASIC_UNIT - 1,

   OQ_LOWERBOUND = OR_UPPERBOUND + 1,
   OQ_UPPERBOUND = OQ_LOWERBOUND + 2*BASIC_UNIT - 1,

   US_LOWERBOUND = OQ_UPPERBOUND + 1,
   US_UPPERBOUND = US_LOWERBOUND + 2*BASIC_UNIT - 1,

   UE_LOWERBOUND = US_UPPERBOUND + 1,
   UE_UPPERBOUND = UE_LOWERBOUND + 2*BASIC_UNIT - 1,

   RN_LOWERBOUND = UE_UPPERBOUND + 1,
   RN_UPPERBOUND = RN_LOWERBOUND + 2*BASIC_UNIT - 1,

   PN_LOWERBOUND = RN_UPPERBOUND + 1,
   PN_UPPERBOUND = PN_LOWERBOUND + 2*BASIC_UNIT - 1,

   VA_LOWERBOUND = PN_UPPERBOUND + 1,
   VA_UPPERBOUND = VA_LOWERBOUND + 2*BASIC_UNIT - 1,

   MR_LOWERBOUND = VA_UPPERBOUND + 1,
   MR_UPPERBOUND = MR_LOWERBOUND + 2*BASIC_UNIT - 1,

   UM_LOWERBOUND = MR_UPPERBOUND + 1,
   UM_UPPERBOUND = UM_LOWERBOUND + 2*BASIC_UNIT - 1,

   UO_LOWERBOUND = UM_UPPERBOUND + 1,
   UO_UPPERBOUND = UO_LOWERBOUND + 2*BASIC_UNIT - 1,

   PE_LOWERBOUND = UO_UPPERBOUND + 1,
   PE_UPPERBOUND = PE_LOWERBOUND + 2*BASIC_UNIT - 1,

   QR_LOWERBOUND = PE_UPPERBOUND + 1,
   QR_UPPERBOUND = QR_LOWERBOUND + 2*BASIC_UNIT - 1,

   JC_LOWERBOUND = QR_UPPERBOUND + 1,
   JC_UPPERBOUND = JC_LOWERBOUND + 2*BASIC_UNIT - 1,

   CONF_LOWERBOUND = JC_UPPERBOUND + 1,
   CONF_UPPERBOUND = CONF_LOWERBOUND + 2*BASIC_UNIT - 1,

   CF_LOWERBOUND = CONF_UPPERBOUND + 1,
   CF_UPPERBOUND = CF_LOWERBOUND + 2*BASIC_UNIT - 1,

   ST_LOWERBOUND = CF_UPPERBOUND + 1,
   ST_UPPERBOUND = ST_LOWERBOUND + 2*BASIC_UNIT - 1,

   STU_LOWERBOUND = ST_UPPERBOUND + 1,
   STU_UPPERBOUND = STU_LOWERBOUND + 2*BASIC_UNIT - 1,

   JG_LOWERBOUND = STU_UPPERBOUND + 1,
   JG_UPPERBOUND = JG_LOWERBOUND + 2*BASIC_UNIT - 1,

   SO_LOWERBOUND = JG_UPPERBOUND + 1,
   SO_UPPERBOUND = SO_LOWERBOUND + 2*BASIC_UNIT - 1,

   QAJ_LOWERBOUND = SO_UPPERBOUND + 1,
   QAJ_UPPERBOUND = QAJ_LOWERBOUND + 2*BASIC_UNIT - 1,

   SPA_LOWERBOUND = QAJ_UPPERBOUND + 1,
   SPA_UPPERBOUND = SPA_LOWERBOUND + 2*BASIC_UNIT - 1,

   REP_LOWERBOUND = SPA_UPPERBOUND + 1,
   REP_UPPERBOUND = REP_LOWERBOUND + 2*BASIC_UNIT - 1,

   UA_LOWERBOUND = REP_UPPERBOUND + 1,
   UA_UPPERBOUND = UA_LOWERBOUND + 2*BASIC_UNIT - 1,

   PR_LOWERBOUND = UA_UPPERBOUND + 1,
   PR_UPPERBOUND = PR_LOWERBOUND + 2*BASIC_UNIT - 1,

   UU_LOWERBOUND = PR_UPPERBOUND + 1,
   UU_UPPERBOUND = UU_LOWERBOUND + 2*BASIC_UNIT - 1,

   GRU_LOWERBOUND = UU_UPPERBOUND + 1,
   GRU_UPPERBOUND = GRU_LOWERBOUND + 2*BASIC_UNIT - 1,

   RESL_LOWERBOUND = GRU_UPPERBOUND + 1,
   RESL_UPPERBOUND = RESL_LOWERBOUND + 2*BASIC_UNIT - 1,

   STN_LOWERBOUND = RESL_UPPERBOUND + 1,
   STN_UPPERBOUND = STN_LOWERBOUND + 2*BASIC_UNIT - 1,

   SC_LOWERBOUND = STN_UPPERBOUND + 1,
   SC_UPPERBOUND = SC_LOWERBOUND + 2*BASIC_UNIT - 1,

   PET_LOWERBOUND = SC_UPPERBOUND + 1,
   PET_UPPERBOUND = PET_LOWERBOUND + 2*BASIC_UNIT - 1,

   PETR_LOWERBOUND = PET_UPPERBOUND + 1,
   PETR_UPPERBOUND = PETR_LOWERBOUND + 2*BASIC_UNIT - 1,

   FPET_LOWERBOUND = PETR_UPPERBOUND + 1,
   FPET_UPPERBOUND = FPET_LOWERBOUND + 2*BASIC_UNIT - 1,

   JR_LOWERBOUND = FPET_UPPERBOUND + 1,
   JR_UPPERBOUND = JR_LOWERBOUND + 2*BASIC_UNIT - 1,

   LIC_LOWERBOUND = JR_UPPERBOUND + 1,
   LIC_UPPERBOUND = LIC_LOWERBOUND + 2*BASIC_UNIT - 1,

   JL_LOWERBOUND = LIC_UPPERBOUND + 1,
   JL_UPPERBOUND = JL_LOWERBOUND + 2*BASIC_UNIT - 1,

   JP_LOWERBOUND = JL_UPPERBOUND + 1,
   JP_UPPERBOUND = JP_LOWERBOUND + 2*BASIC_UNIT - 1,

   JO_LOWERBOUND = JP_UPPERBOUND + 1,
   JO_UPPERBOUND = JO_LOWERBOUND + 2*BASIC_UNIT - 1,

   UPU_LOWERBOUND = JO_UPPERBOUND + 1,
   UPU_UPPERBOUND = UPU_LOWERBOUND + 2*BASIC_UNIT - 1,

   CK_LOWERBOUND = UPU_UPPERBOUND + 1,
   CK_UPPERBOUND = CK_LOWERBOUND + 2*BASIC_UNIT - 1,

   KRB_LOWERBOUND = CK_UPPERBOUND + 1,
   KRB_UPPERBOUND = KRB_LOWERBOUND + 2*BASIC_UNIT - 1,

   PA_LOWERBOUND = KRB_UPPERBOUND + 1,
   PA_UPPERBOUND = PA_LOWERBOUND + 2*BASIC_UNIT - 1,

   JRE_LOWERBOUND = PA_UPPERBOUND + 1,
   JRE_UPPERBOUND = JRE_LOWERBOUND + 2*BASIC_UNIT - 1,

   ID_LOWERBOUND = JRE_UPPERBOUND + 1,
   ID_UPPERBOUND = ID_LOWERBOUND + 2*BASIC_UNIT - 1,

   MA_LOWERBOUND = ID_UPPERBOUND + 1,
   MA_UPPERBOUND = MA_LOWERBOUND + 2*BASIC_UNIT - 1,

   TE_LOWERBOUND = MA_UPPERBOUND + 1,
   TE_UPPERBOUND = TE_LOWERBOUND + 2*BASIC_UNIT - 1,

   CAL_LOWERBOUND = TE_UPPERBOUND + 1,
   CAL_UPPERBOUND = CAL_LOWERBOUND + 2*BASIC_UNIT - 1,

   CA_LOWERBOUND = CAL_UPPERBOUND + 1,
   CA_UPPERBOUND = CA_LOWERBOUND + 2*BASIC_UNIT - 1,

   TMR_LOWERBOUND = CA_UPPERBOUND + 1,
   TMR_UPPERBOUND = TMR_LOWERBOUND + 2*BASIC_UNIT - 1,

   TM_LOWERBOUND = TMR_UPPERBOUND + 1,
   TM_UPPERBOUND = TM_LOWERBOUND + 2*BASIC_UNIT - 1,

   RT_LOWERBOUND = TM_UPPERBOUND + 1,
   RT_UPPERBOUND = RT_LOWERBOUND + 2*BASIC_UNIT - 1,

   UPP_LOWERBOUND = RT_UPPERBOUND + 1,
   UPP_UPPERBOUND = UPP_LOWERBOUND + 2*BASIC_UNIT - 1,

   KTGT_LOWERBOUND = UPP_UPPERBOUND + 1,
   KTGT_UPPERBOUND = KTGT_LOWERBOUND + 2*BASIC_UNIT - 1,

   SME_LOWERBOUND = KTGT_UPPERBOUND + 1,
   SME_UPPERBOUND = SME_LOWERBOUND + 2*BASIC_UNIT - 1,

   MES_LOWERBOUND = SME_UPPERBOUND + 1,
   MES_UPPERBOUND = MES_LOWERBOUND + 2*BASIC_UNIT - 1,

   JAT_LOWERBOUND = MES_UPPERBOUND + 1,
   JAT_UPPERBOUND = JAT_LOWERBOUND + 2*BASIC_UNIT - 1,

   CT_LOWERBOUND = JAT_UPPERBOUND + 1,
   CT_UPPERBOUND = CT_LOWERBOUND + 2*BASIC_UNIT - 1,

   SGEJ_LOWERBOUND = CT_UPPERBOUND + 1,
   SGEJ_UPPERBOUND = SGEJ_LOWERBOUND + 2*BASIC_UNIT - 1,

   ULNG_LOWERBOUND = SGEJ_UPPERBOUND + 1,
   ULNG_UPPERBOUND = ULNG_LOWERBOUND + 2*BASIC_UNIT - 1,

   HGRP_LOWERBOUND = ULNG_UPPERBOUND + 1,
   HGRP_UPPERBOUND = HGRP_LOWERBOUND + 2*BASIC_UNIT - 1,

   HR_LOWERBOUND = HGRP_UPPERBOUND + 1,
   HR_UPPERBOUND = HR_LOWERBOUND + 2*BASIC_UNIT - 1,

   PERM_LOWERBOUND = HR_UPPERBOUND + 1,
   PERM_UPPERBOUND = PERM_LOWERBOUND + 2*BASIC_UNIT - 1,

   LS_LOWERBOUND = PERM_UPPERBOUND + 1,
   LS_UPPERBOUND = LS_LOWERBOUND + 2*BASIC_UNIT - 1,

   RU_LOWERBOUND = LS_UPPERBOUND + 1,
   RU_UPPERBOUND = RU_LOWERBOUND + 2*BASIC_UNIT - 1,

   FES_LOWERBOUND = RU_UPPERBOUND + 1,
   FES_UPPERBOUND = FES_LOWERBOUND + 2*BASIC_UNIT - 1,

   SU_LOWERBOUND = FES_UPPERBOUND + 1,
   SU_UPPERBOUND = SU_LOWERBOUND + 2*BASIC_UNIT - 1,

   SPC_LOWERBOUND = SU_UPPERBOUND + 1,
   SPC_UPPERBOUND = SPC_LOWERBOUND + 2*BASIC_UNIT - 1,

   SPR_LOWERBOUND = SPC_UPPERBOUND + 1,
   SPR_UPPERBOUND = SPR_LOWERBOUND + 2*BASIC_UNIT - 1,

   SPT_LOWERBOUND = SPR_UPPERBOUND + 1,
   SPT_UPPERBOUND = SPT_LOWERBOUND + 2*BASIC_UNIT - 1,

   SPTR_LOWERBOUND = SPT_UPPERBOUND + 1,
   SPTR_UPPERBOUND = SPTR_LOWERBOUND + 2*BASIC_UNIT - 1,

   JJ_LOWERBOUND = SPTR_UPPERBOUND + 1,
   JJ_UPPERBOUND = JJ_LOWERBOUND + 2*BASIC_UNIT - 1,

   JJAT_LOWERBOUND = JJ_UPPERBOUND + 1,
   JJAT_UPPERBOUND = JJAT_LOWERBOUND + 2*BASIC_UNIT - 1,

   NSV_LOWERBOUND = JJAT_UPPERBOUND + 1,
   NSV_UPPERBOUND = NSV_LOWERBOUND + 2*BASIC_UNIT - 1,

   ASTR_LOWERBOUND = NSV_UPPERBOUND + 1,
   ASTR_UPPERBOUND = ASTR_LOWERBOUND + 2*BASIC_UNIT - 1,

   AULNG_LOWERBOUND = ASTR_UPPERBOUND + 1,
   AULNG_UPPERBOUND = AULNG_LOWERBOUND + 2*BASIC_UNIT - 1,

   ABOOL_LOWERBOUND = AULNG_UPPERBOUND + 1,
   ABOOL_UPPERBOUND = ABOOL_LOWERBOUND + 2*BASIC_UNIT - 1,

   ATIME_LOWERBOUND = ABOOL_UPPERBOUND + 1,
   ATIME_UPPERBOUND = ATIME_LOWERBOUND + 2*BASIC_UNIT - 1,

   AMEM_LOWERBOUND = ATIME_UPPERBOUND + 1,
   AMEM_UPPERBOUND = AMEM_LOWERBOUND + 2*BASIC_UNIT - 1,

   AINTER_LOWERBOUND = AMEM_UPPERBOUND + 1,
   AINTER_UPPERBOUND = AINTER_LOWERBOUND + 2*BASIC_UNIT - 1,

   ASTRING_LOWERBOUND = AINTER_UPPERBOUND + 1,
   ASTRING_UPPERBOUND = ASTRING_LOWERBOUND + 2*BASIC_UNIT - 1,

   ASTRLIST_LOWERBOUND = ASTRING_UPPERBOUND + 1,
   ASTRLIST_UPPERBOUND = ASTRLIST_LOWERBOUND + 2*BASIC_UNIT - 1,

   AUSRLIST_LOWERBOUND = ASTRLIST_UPPERBOUND + 1,
   AUSRLIST_UPPERBOUND = AUSRLIST_LOWERBOUND + 2*BASIC_UNIT - 1,

   APRJLIST_LOWERBOUND = AUSRLIST_UPPERBOUND + 1,
   APRJLIST_UPPERBOUND = APRJLIST_LOWERBOUND + 2*BASIC_UNIT - 1,

   ACELIST_LOWERBOUND = APRJLIST_UPPERBOUND + 1,
   ACELIST_UPPERBOUND = ACELIST_LOWERBOUND + 2*BASIC_UNIT - 1,

   ASOLIST_LOWERBOUND = ACELIST_UPPERBOUND + 1,
   ASOLIST_UPPERBOUND = ASOLIST_LOWERBOUND + 2*BASIC_UNIT - 1,

   AQTLIST_LOWERBOUND = ASOLIST_UPPERBOUND + 1,
   AQTLIST_UPPERBOUND = AQTLIST_LOWERBOUND + 2*BASIC_UNIT - 1,

   CQ_LOWERBOUND = AQTLIST_UPPERBOUND + 1,
   CQ_UPPERBOUND = CQ_LOWERBOUND + 3*BASIC_UNIT - 1,

   QIM_LOWERBOUND = CQ_UPPERBOUND + 1,
   QIM_UPPERBOUND = QIM_LOWERBOUND + 2*BASIC_UNIT - 1,

   FCAT_LOWERBOUND = QIM_UPPERBOUND + 1,
   FCAT_UPPERBOUND = FCAT_LOWERBOUND + 2*BASIC_UNIT - 1,

   CTI_LOWERBOUND = FCAT_UPPERBOUND + 1,
   CTI_UPPERBOUND = CTI_LOWERBOUND + 2*BASIC_UNIT - 1,

   PARA_LOWERBOUND = CTI_UPPERBOUND + 1,
   PARA_UPPERBOUND = PARA_LOWERBOUND + 2*BASIC_UNIT - 1,

   XMLA_LOWERBOUND = PARA_UPPERBOUND + 1,
   XMLA_UPPERBOUND = XMLA_LOWERBOUND + 2*BASIC_UNIT - 1,

   XMLH_LOWERBOUND = XMLA_UPPERBOUND + 1,
   XMLH_UPPERBOUND = XMLH_LOWERBOUND + 2*BASIC_UNIT - 1,

   XMLS_LOWERBOUND = XMLH_UPPERBOUND + 1,
   XMLS_UPPERBOUND = XMLS_LOWERBOUND + 2*BASIC_UNIT - 1,

   XMLE_LOWERBOUND = XMLS_UPPERBOUND + 1,
   XMLE_UPPERBOUND = XMLE_LOWERBOUND + 2*BASIC_UNIT - 1,

   RDE_LOWERBOUND = XMLE_UPPERBOUND + 1,
   RDE_UPPERBOUND = RDE_LOWERBOUND + 2*BASIC_UNIT - 1,

   RUE_LOWERBOUND = RDE_UPPERBOUND + 1,
   RUE_UPPERBOUND = RUE_LOWERBOUND + 2*BASIC_UNIT - 1,

   QETI_LOWERBOUND = RUE_UPPERBOUND + 1,
   QETI_UPPERBOUND = QETI_LOWERBOUND + 2*BASIC_UNIT - 1,

   LDR_LOWERBOUND = QETI_UPPERBOUND + 1,
   LDR_UPPERBOUND = LDR_LOWERBOUND + 2*BASIC_UNIT - 1,

   QRL_LOWERBOUND = LDR_UPPERBOUND + 1,
   QRL_UPPERBOUND = QRL_LOWERBOUND + 2*BASIC_UNIT - 1,

   CCT_LOWERBOUND = QRL_UPPERBOUND + 1,
   CCT_UPPERBOUND = CCT_LOWERBOUND + 2*BASIC_UNIT - 1,

   CQU_LOWERBOUND = CCT_UPPERBOUND + 1,
   CQU_UPPERBOUND = CQU_LOWERBOUND + 2*BASIC_UNIT - 1,

   SCT_LOWERBOUND = CQU_UPPERBOUND + 1,
   SCT_UPPERBOUND = SCT_LOWERBOUND + 2*BASIC_UNIT - 1,

   REF_LOWERBOUND = SCT_UPPERBOUND + 1,
   REF_UPPERBOUND = REF_LOWERBOUND + 2*BASIC_UNIT - 1,

   RQS_LOWERBOUND = REF_UPPERBOUND + 1,
   RQS_UPPERBOUND = RQS_LOWERBOUND + 2*BASIC_UNIT - 1,

   RQR_LOWERBOUND = RQS_UPPERBOUND + 1,
   RQR_UPPERBOUND = RQR_LOWERBOUND + 2*BASIC_UNIT - 1,

   RQRF_LOWERBOUND = RQR_UPPERBOUND + 1,
   RQRF_UPPERBOUND = RQRF_LOWERBOUND + 2*BASIC_UNIT - 1,

   RQRL_LOWERBOUND = RQRF_UPPERBOUND + 1,
   RQRL_UPPERBOUND = RQRL_LOWERBOUND + 2*BASIC_UNIT - 1,

   RQL_LOWERBOUND = RQRL_UPPERBOUND + 1,
   RQL_UPPERBOUND = RQL_LOWERBOUND + 2*BASIC_UNIT - 1,

   AR_LOWERBOUND = RQL_UPPERBOUND + 1,
   AR_UPPERBOUND = AR_LOWERBOUND + 2*BASIC_UNIT - 1,

   ARA_LOWERBOUND = AR_UPPERBOUND + 1,
   ARA_UPPERBOUND = ARA_LOWERBOUND + 2*BASIC_UNIT - 1,

   ACK_LOWERBOUND = ARA_UPPERBOUND + 1,
   ACK_UPPERBOUND = ACK_LOWERBOUND + 2*BASIC_UNIT - 1,

   EVR_LOWERBOUND = ACK_UPPERBOUND + 1,
   EVR_UPPERBOUND = EVR_LOWERBOUND + 2*BASIC_UNIT - 1,

   JSV_LOWERBOUND = EVR_UPPERBOUND + 1,
   JSV_UPPERBOUND = JSV_LOWERBOUND + 2*BASIC_UNIT - 1,

   RTIC_LOWERBOUND = JSV_UPPERBOUND + 1,
   RTIC_UPPERBOUND = RTIC_LOWERBOUND + 2*BASIC_UNIT - 1,

   PRO_LOWERBOUND = RTIC_UPPERBOUND + 1,
   PRO_UPPERBOUND = PRO_LOWERBOUND + 2*BASIC_UNIT - 1,

   GR_LOWERBOUND = PRO_UPPERBOUND + 1,
   GR_UPPERBOUND = GR_LOWERBOUND + 2*BASIC_UNIT - 1,

   BN_LOWERBOUND = GR_UPPERBOUND + 1,
   BN_UPPERBOUND = BN_LOWERBOUND + 2*BASIC_UNIT - 1,

   PACK_LOWERBOUND = BN_UPPERBOUND + 1,
   PACK_UPPERBOUND = PACK_LOWERBOUND + 2*BASIC_UNIT - 1,

};

