#!/bin/sh
#___INFO__MARK_BEGIN__
##########################################################################
#
#  The Contents of this file are made available subject to the terms of
#  the Sun Industry Standards Source License Version 1.2
#
#  Sun Microsystems Inc., March, 2001
#
#
#  Sun Industry Standards Source License Version 1.2
#  =================================================
#  The contents of this file are subject to the Sun Industry Standards
#  Source License Version 1.2 (the "License"); You may not use this file
#  except in compliance with the License. You may obtain a copy of the
#  License at http://gridengine.sunsource.net/Gridengine_SISSL_license.html
#
#  Software provided under this License is provided on an "AS IS" basis,
#  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
#  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
#  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
#  See the License for the specific provisions governing your rights and
#  obligations concerning the Software.
#
#  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
#
#  Copyright: 2001 by Sun Microsystems, Inc.
#
#  All Rights Reserved.
#
##########################################################################
#___INFO__MARK_END__
#
# Credit should be given to Robert Manchek manchek@CS.UTK.EDU for creating
# a similar aimk procedure for the PVM 3.x distribution, Jul 22 1991,
# which inspired the Cluster Scheduler aimk build scheme.

# Make sure to avoid confusion between shell variables and environment
# variables
#

dir=`dirname $0`
basedir=`cd $dir/..; pwd`

usage() {
   echo ""
   echo "usage: compilearch (-b|-t|-c) [<arch>]"
   echo ""
   echo "  -b  print the build arch (SOLARIS64)"
   echo "  -t  print the target bits (TARGET_32BIT or TARGET_64BIT)"
   echo "  -c  print the compile arch (e.g LINUXIA64_24) or an empty"
   echo "      string if the build arch is equal to the compile arch"
   echo ""
   echo "  <arch> print the information for a specific architecture."
   echo "         If <arch> is missing the architecture is determined"
   echo "         by calling the dist/util/arch script"
   echo ""
}

buildarch=""
option=""

case $# in
  0) usage; exit 1;;
  1)
    case $1 in
      -b) option="-b";;
      -t) option="-t";;
      -c) option="-c";;
      *)  usage; exit 1;;
    esac;;
  2)
    option=$1; buildarch=$2;;
  *)
     usage
     exit 1;;
esac

if [ "$buildarch" = "" ]; then
   archscript=$basedir/dist/util/arch
   if [ -f $archscript ]; then
      buildarch=`$archscript`
      if [ $? -ne 0 ]; then
          echo "error in $archscript: $buildarch"
          exit 1
      fi
   else
      echo script $archscript not available
      exit 1
   fi
fi

COMPILE_ARCH=
BUILDARCH=
TARGET_BITS=

# Map buildarch into uppercase BUILDARCH
#
case $buildarch in
   darwin-x64)
      BUILDARCH=DARWIN_X64
      TARGET_BITS=TARGET_64BIT
      ;;
   darwin-arm64)
      BUILDARCH=DARWIN_ARM64
      TARGET_BITS=TARGET_64BIT
      ;;
   fbsd-amd64)
      BUILDARCH=FREEBSD_AMD64
      TARGET_BITS=TARGET_64BIT
      ;;
   fbsd-sparc64)
      BUILDARCH=FREEBSD_SPARC64
      ;;
   lx-amd64)
      BUILDARCH=LINUXAMD64
      COMPILE_ARCH=LINUXAMD64
      TARGET_BITS=TARGET_64BIT
      ;;
   lx-arm6)
      BUILDARCH=LINUXARM6
      COMPILE_ARCH=LINUXARM6
      TARGET_BITS=TARGET_32BIT
      ;;
   lx-arm7)
      BUILDARCH=LINUXARM7
      COMPILE_ARCH=LINUXARM7
      TARGET_BITS=TARGET_32BIT
      ;;
   lx-arm64)
      BUILDARCH=LINUXARM64
      COMPILE_ARCH=LINUXARM64
      TARGET_BITS=TARGET_64BIT
      ;;
   lx-armhf)
      BUILDARCH=LINUXARMHF
      COMPILE_ARCH=LINUXARMHF
      TARGET_BITS=TARGET_32BIT
      ;;
   lx-ppc64le)
      BUILDARCH=LINUXPPC64LE
      COMPILE_ARCH=LINUXPPC64LE
      TARGET_BITS=TARGET_64BIT
      ;;
   lx-s390x)
      BUILDARCH=LINUXS390X
      COMPILE_ARCH=LINUXS390X
      TARGET_BITS=TARGET_64BIT
      ;;
   lx-sparc64)
      BUILDARCH=LINUXSPARC64
      COMPILE_ARCH=LINUXSPARC64
      TARGET_BITS=TARGET_64BIT
      ;;
   ulx-amd64)
      BUILDARCH=LINUXAMD64
      COMPILE_ARCH=ULINUXAMD64
      TARGET_BITS=TARGET_64BIT
      ;;
   ulx-sparc64)
      BUILDARCH=LINUXSPARC64
      COMPILE_ARCH=ULINUXSPARC64
      TARGET_BITS=TARGET_64BIT
      ;;
   xlx-amd64)
      BUILDARCH=LINUXAMD64
      COMPILE_ARCH=ULINUXAMD64
      TARGET_BITS=TARGET_64BIT
      ;;
   nbsd-sparc64)
      BUILDARCH=NETBSD_SPARC64
      TARGET_BITS=TARGET_64BIT
      ;;
   nbsd-x86_64)
      BUILDARCH=NETBSD_X86_64
      TARGET_BITS=TARGET_64BIT
      ;;
   sol-sparc64)
      BUILDARCH=SOLARIS64
      TARGET_BITS=TARGET_64BIT
      ;;
   sol-amd64|osol-amd64)
      BUILDARCH=SOLARISAMD64
      TARGET_BITS=TARGET_64BIT
      ;;
   usol-sparc64)
      BUILDARCH=SOLARIS64
      COMPILE_ARCH=USOLARIS64
      TARGET_BITS=TARGET_64BIT
      ;;
   usol-amd64)
      BUILDARCH=SOLARISAMD64
      COMPILE_ARCH=USOLARISAMD64
      TARGET_BITS=TARGET_64BIT
      ;;
   lx-riscv64)
      BUILDARCH=LINUXRISCV64
      COMPILE_ARCH=LINUXRISCV64
      TARGET_BITS=TARGET_64BIT
      ;;
   lx-loong64)
      BUILDARCH=LINUXLOONG64
      COMPILE_ARCH=LINUXLOONG64
      TARGET_BITS=TARGET_64BIT
      ;;
   *)
      echo cannot compile - no mapping for architecture \"$buildarch\" defined yet
      exit 1
      ;;
esac

case "$option" in
  -b) echo $BUILDARCH;;
  -t) echo $TARGET_BITS;;
  -c) echo $COMPILE_ARCH;;
  *)
    echo "invalid option $option"
    exit 1;;
esac

