#pragma once
/*___INFO__MARK_BEGIN_NEW__*/
/***************************************************************************
 *
 *  Copyright 2026 HPC-Gridware GmbH
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 ***************************************************************************/
/*___INFO__MARK_END_NEW__*/

#include <cstdint>

#include "cull/cull.h"
#include "uti/sge_monitor.h"

/** Apply the per-finish bookkeeping that, in the pre-CS-1239 scheme, was
 *  generated by the scheduler thread as the three orders ORT_update_user_usage,
 *  ORT_update_project_usage, and ORT_remove_job, and applied in worker threads
 *  via sge_follow_order.
 *
 *  Called from inside sge_commit_job's COMMIT_ST_FINISHED_FAILED_EE case, after
 *  the JAT_status = JFINISHED transition and before sge_bury_job. External
 *  callers should never invoke this helper directly - sge_commit_job is the
 *  contract.
 *
 *  Preconditions: caller holds LOCK_GLOBAL (write); JAT_status is JFINISHED.
 *
 *  Steps:
 *    - resolve user / project refs;
 *    - sum the job's final scaled usage into UU_usage (or
 *      user.UU_project[project].UPP_usage when project is set), UU_long_term_usage
 *      / UPP_long_term_usage, PR_usage, and PR_long_term_usage. Catches up the
 *      decay since the last TET tick first, so the historical part stays in sync;
 *    - drop the job's entry from UU_debited_job_usage / PR_debited_job_usage
 *      (the job is gone, the tracking record must follow);
 *    - bump UU_version / PR_version (the change marker). UU_/PR_usage_seqno
 *      is deliberately NOT touched: it is the periodic decay handler's
 *      idempotency stamp; sharing it with the change marker would silently
 *      collide with the handler's run counter and skip decay ticks;
 *    - mark the (user, project) dirty for the TET sharetree-spool handler,
 *      which batches the sgeE_USER_MOD / sgeE_PROJECT_MOD events and the spool
 *      writes with sgeE_NEW_SHARETREE under one event-master transaction;
 *    - mark the master share tree dirty so the next TET tick republishes it.
 *
 *  Returns 0 on success, a negative value on a hard error (missing jep/jatep).
 */
int sge_book_finished_job_usage(lListElem *jep, lListElem *jatep, monitoring_t *monitor, uint64_t gdi_session);

/** CS-1908 finished-job retention: drop any pending retention-sweep event and
 *  re-queue at +5 s so a runtime qconf -mconf change to a finished_jobs_*
 *  tunable takes effect within seconds rather than up to sweep_interval away.
 *  Called from configuration_qmaster.cc after the config has been swapped in.
 *
 *  When both retention tunables are 0 at reschedule time (feature just turned
 *  off) the requeued event carries sweep_all=1 so the next tick drains any
 *  retained ja_tasks left over from the previous retention window instead of
 *  stranding them on master_job_list. Otherwise the requeue is a normal
 *  sweep_all=0 event.
 *
 *  Lives in ocs_FinishedJob.cc rather than sge_thread_timer.cc so consumers
 *  that do not link the timed-event thread's full translation unit (e.g.
 *  lightweight test binaries such as test_qmaster_calendar) can still resolve
 *  the symbol. The sweep handler itself remains in sge_thread_timer.cc.
 *  Mirrors the CS-1239 split between sge_sharetree_tick_handler
 *  (sge_thread_timer.cc) and sge_reschedule_sharetree_tick (ocs_SharetreeUsage.cc).
 */
void sge_reschedule_finished_jobs_sweep();
