#pragma once
/*___INFO__MARK_BEGIN_NEW__*/
/***************************************************************************
 *
 *  Copyright 2026 HPC-Gridware GmbH
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 ***************************************************************************/
/*___INFO__MARK_END_NEW__*/

#include <cstdint>

#include "cull/cull.h"
#include "uti/sge_monitor.h"

/** Apply the per-finish bookkeeping that, in the pre-CS-1239 scheme, was
 *  generated by the scheduler thread as the three orders ORT_update_user_usage,
 *  ORT_update_project_usage, and ORT_remove_job, and applied in worker threads
 *  via sge_follow_order.
 *
 *  Preconditions: caller holds LOCK_GLOBAL (write); sge_commit_job with mode
 *  COMMIT_ST_FINISHED_FAILED_EE has already set JAT_status = JFINISHED.
 *
 *  Steps:
 *    - resolve user / project refs;
 *    - sum the job's final scaled usage into UU_usage (or
 *      user.UU_project[project].UPP_usage when project is set), UU_long_term_usage
 *      / UPP_long_term_usage, PR_usage, and PR_long_term_usage. No decay - that
 *      is the TET decay task's job;
 *    - drop the job's entry from UU_debited_job_usage / PR_debited_job_usage
 *      (the job is gone, the tracking record must follow);
 *    - bump UU_version / PR_version (the change marker). UU_/PR_usage_seqno
 *      is deliberately NOT touched: it is the periodic decay handler's
 *      idempotency stamp; sharing it with the change marker would silently
 *      collide with the handler's run counter and skip decay ticks;
 *    - emit sgeE_USER_MOD / sgeE_PROJECT_MOD events with spool deferred to the
 *      TET flush task in ocs::SharetreeUsage;
 *    - mark the (user, project) dirty for that flush;
 *    - sge_commit_job with COMMIT_ST_DEBITED_EE to bury the ja_task / job,
 *      spool the removal, and emit sgeE_JOB_DEL / sgeE_JATASK_DEL.
 *
 *  Returns 0 on success, a negative value on a hard error (missing jep/jatep).
 */
int sge_book_finished_job_usage(lListElem *jep, lListElem *jatep, monitoring_t *monitor, uint64_t gdi_session);
